# Generated by Django 3.1.4 on 2020-12-27 14:43

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Records',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=50, verbose_name='From')),
                ('file_desc', models.CharField(max_length=100, verbose_name='File Content')),
                ('date_created', models.DateField(default=datetime.datetime(2020, 12, 27, 14, 43, 48, 928212, tzinfo=utc), verbose_name='Date Created')),
                ('action_desc', models.CharField(max_length=100, verbose_name='Action Taken')),
                ('status', models.CharField(max_length=100, verbose_name='Status')),
            ],
        ),
    ]
