# Generated by Django 3.1.4 on 2020-12-30 10:02

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('EnvergaDB', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='records',
            name='date_created',
            field=models.DateField(default=datetime.datetime(2020, 12, 30, 10, 2, 56, 105244, tzinfo=utc), verbose_name='Date Created'),
        ),
        migrations.AlterField(
            model_name='records',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Acknowledged', 'Acknowledged'), ('Endorsed', 'Endorsed'), ('Recommended to President', 'Recommended to President'), ('Approved', 'Approved'), ('Denied', 'Denied'), ('Returned', 'Returned')], default='Pending', max_length=50, verbose_name='Status'),
        ),
    ]
