# Generated by Django 3.1.4 on 2020-12-30 10:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('EnvergaDB', '0002_auto_20201230_1802'),
    ]

    operations = [
        migrations.AlterField(
            model_name='records',
            name='date_created',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Date Created'),
        ),
    ]
