# Generated by Django 3.1.4 on 2021-08-18 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EnvergaDB', '0005_auto_20201230_2306'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='records',
            name='action_desc',
        ),
        migrations.RemoveField(
            model_name='records',
            name='file_desc',
        ),
        migrations.AddField(
            model_name='records',
            name='description',
            field=models.CharField(default='No description added', max_length=100, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='records',
            name='author',
            field=models.CharField(max_length=50, verbose_name='Author'),
        ),
    ]
