# Generated by Django 3.1.4 on 2021-09-25 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EnvergaDB', '0006_auto_20210818_1844'),
    ]

    operations = [
        migrations.AlterField(
            model_name='records',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Acknowledged', 'Acknowledged'), ('Endorsed', 'Endorsed'), ('Recommended to President', 'Recommended to President'), ('Approved', 'Approved'), ('Denied', 'Denied'), ('Returned', 'Returned')], default='Pending', max_length=100, verbose_name='Status'),
        ),
    ]
